version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
    command: sleep infinity
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/nestjs_db?schema=public
      - NODE_ENV=development

  # PostgreSQL Database (Currently Active)
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nestjs_db
    ports:
      - "5432:5432"
    networks:
      - app-network

  # MongoDB Database (Commented - Uncomment to use MongoDB instead of PostgreSQL)
  # db:
  #   image: mongo:7.0
  #   restart: unless-stopped
  #   volumes:
  #     - mongodb-data:/data/db
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=admin
  #     - MONGO_INITDB_ROOT_PASSWORD=password
  #     - MONGO_INITDB_DATABASE=nestjs_db
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - app-network

volumes:
  postgres-data:
  # mongodb-data:  # Uncomment when using MongoDB

networks:
  app-network:
    driver: bridge
